package greeen.views;
 
import java.text.DateFormat;
import java.text.SimpleDateFormat; 
import java.util.Date; 
import javax.swing.ImageIcon;
import javax.swing.JFrame; 
   
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent; 
/**
 *
 * @author deidine
 */
public final class FristPage extends javax.swing.JFrame {

    String username;
    DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    boolean valideQuentite = false;
    int currentStock = 0;
    Double moneyToCaisse = 0.0;
    Date dates = new Date();
//    private boolean canLoan;
 
    /**
     * Creates new form test2
     *
     * @param username
     */
    public FristPage(String username) {

        initComponents();

        this.username = username;
     
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
 
        // setIconImage(new ImageIcon("resources/logo.png").getImage());
     
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                if (moneyToCaisse > 0.0) {
                   
                    moneyToCaisse = 0.0;

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnSalle2 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCaisse = new javax.swing.JButton();
        btnSalle3 = new javax.swing.JButton();
        btnSalle4 = new javax.swing.JButton();
        jMenuBarInfoPengembang = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        infoAplikasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        btnSalle2.setBackground(new java.awt.Color(0, 0, 255));
        btnSalle2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnSalle2.setForeground(new java.awt.Color(255, 255, 255));
        btnSalle2.setText("Stock Achat");
        btnSalle2.setBorderPainted(false);
        btnSalle2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalle2ActionPerformed(evt);
            }
        });

        jPanel14.setForeground(new java.awt.Color(0, 204, 153));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        btnCaisse.setBackground(new java.awt.Color(0, 204, 0));
        btnCaisse.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnCaisse.setForeground(new java.awt.Color(255, 255, 255));
        btnCaisse.setText("afficher  les information du stock");
        btnCaisse.setBorderPainted(false);
        btnCaisse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaisse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaisseActionPerformed(evt);
            }
        });

        btnSalle3.setBackground(new java.awt.Color(153, 0, 153));
        btnSalle3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnSalle3.setForeground(new java.awt.Color(255, 255, 255));
        btnSalle3.setText("Stock de vente");
        btnSalle3.setBorderPainted(false);
        btnSalle3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalle3ActionPerformed(evt);
            }
        });

        btnSalle4.setBackground(new java.awt.Color(255, 0, 0));
        btnSalle4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnSalle4.setForeground(new java.awt.Color(255, 255, 255));
        btnSalle4.setText("fermer caisse");
        btnSalle4.setBorderPainted(false);
        btnSalle4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalle4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btnCaisse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalle2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnSalle3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(btnSalle4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1042, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCaisse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalle2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSalle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnSalle4, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(600, 600, 600))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel15);

        jMenu1.setText("File");

        jMenuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuLogout.setText("Log Out");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLogout);

        jMenuBarInfoPengembang.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Info Pengembang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        infoAplikasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        infoAplikasi.setText("Info Aplikasi");
        infoAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoAplikasiActionPerformed(evt);
            }
        });
        jMenu2.add(infoAplikasi);

        jMenuBarInfoPengembang.add(jMenu2);

        setJMenuBar(jMenuBarInfoPengembang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaisseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaisseActionPerformed
    new Dashboard(username).setVisible(true);      
            dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_btnCaisseActionPerformed

    private void btnSalle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalle2ActionPerformed
        new PurchaseStock(username).setVisible(true); 
          this.dispose();     
 
    }//GEN-LAST:event_btnSalle2ActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void infoAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoAplikasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoAplikasiActionPerformed

    private void btnSalle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalle3ActionPerformed

        new SalleStcok(username).setVisible(true);  
          this.dispose();    
    }//GEN-LAST:event_btnSalle3ActionPerformed

    private void btnSalle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalle4ActionPerformed
            dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalle4ActionPerformed

    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaisse;
    private javax.swing.JButton btnSalle2;
    private javax.swing.JButton btnSalle3;
    private javax.swing.JButton btnSalle4;
    private javax.swing.JMenuItem infoAplikasi;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarInfoPengembang;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
 
}
