/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package greeen.views;



import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import greeen.doa.InputPurchaseProductDAO;
import greeen.doa.ProductDAO;
import greeen.utils.ProductTable;
import greeen.utils.PurcahseTable;
import greeen.utils.SalleTable;

/**
 *
 * @author deidine
 */
public class SalleStcok extends javax.swing.JFrame {

    private static int counterPagination = 0;
    int limitPagination = 20;
    
    PurcahseTable prchtb; 

    ProductTable prtbl = new ProductTable("salle");
    
    
    /**
     * Creates new form Dashboard2
     */
    static String username="deodone";

    public SalleStcok(String username) {
        this.username = username; 
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon("resources/logo.png").getImage());

        // setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        try {
            loadData();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        setExtendedState(JFrame.MAXIMIZED_BOTH); // this for full screen
        // setUndecorated(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        serchSalle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nextPurchase1 = new javax.swing.JButton();
        prevSalle = new javax.swing.JButton();
        deleteSalle = new javax.swing.JButton();
        addSalle = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        sallePAge2 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollTabelTransaksi8 = new javax.swing.JScrollPane();
        tabelSalle = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        serchInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nextInput = new javax.swing.JButton();
        prevInput = new javax.swing.JButton();
        deleteInput = new javax.swing.JButton();
        addInput = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel18 = new javax.swing.JPanel();
        jScrollTabelTransaksi11 = new javax.swing.JScrollPane();
        tabelInput = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        serchProduct = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nextProduct = new javax.swing.JButton();
        prevProduct = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jScrollTabelTransaksi9 = new javax.swing.JScrollPane();
        tabelProduit = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        serchSalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serchSalleKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("Chercher");

        nextPurchase1.setBackground(new java.awt.Color(255, 255, 204));
        nextPurchase1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        nextPurchase1.setForeground(new java.awt.Color(51, 51, 0));
        nextPurchase1.setText("Next");
        nextPurchase1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        nextPurchase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPurchase1ActionPerformed(evt);
            }
        });

        prevSalle.setBackground(new java.awt.Color(255, 255, 204));
        prevSalle.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        prevSalle.setForeground(new java.awt.Color(51, 51, 0));
        prevSalle.setText("Prev");
        prevSalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        prevSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevSalleActionPerformed(evt);
            }
        });

        deleteSalle.setBackground(new java.awt.Color(255, 51, 51));
        deleteSalle.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        deleteSalle.setForeground(new java.awt.Color(51, 51, 0));
        deleteSalle.setText("suprimer");
        deleteSalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        deleteSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSalleActionPerformed(evt);
            }
        });

        addSalle.setBackground(new java.awt.Color(51, 255, 51));
        addSalle.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        addSalle.setForeground(new java.awt.Color(51, 0, 51));
        addSalle.setText("Ajouter");
        addSalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalleActionPerformed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(102, 102, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setForeground(new java.awt.Color(102, 102, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator13.setForeground(new java.awt.Color(102, 102, 0));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        sallePAge2.setBackground(new java.awt.Color(0, 204, 255));
        sallePAge2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        sallePAge2.setForeground(new java.awt.Color(255, 255, 255));
        sallePAge2.setText("Retour");
        sallePAge2.setBorderPainted(false);
        sallePAge2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sallePAge2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(addSalle)
                .addGap(32, 32, 32)
                .addComponent(deleteSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sallePAge2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(prevSalle)
                .addGap(31, 31, 31)
                .addComponent(nextPurchase1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(serchSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sallePAge2)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(serchSalle, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(addSalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(deleteSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prevSalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextPurchase1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabelSalle.setOpaque(true);
        tabelSalle.setRowHeight(30);
        tabelSalle.getTableHeader().setReorderingAllowed(false);
        jScrollTabelTransaksi8.setViewportView(tabelSalle);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi8)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi8, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stock de Vente", jPanel4);

        jPanel17.setBackground(new java.awt.Color(51, 0, 51));

        serchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serchInputKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("Chercher");

        nextInput.setBackground(new java.awt.Color(255, 255, 204));
        nextInput.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        nextInput.setForeground(new java.awt.Color(51, 51, 0));
        nextInput.setText("Next");
        nextInput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        nextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInputActionPerformed(evt);
            }
        });

        prevInput.setBackground(new java.awt.Color(255, 255, 204));
        prevInput.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        prevInput.setForeground(new java.awt.Color(51, 51, 0));
        prevInput.setText("Prev");
        prevInput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        prevInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevInputActionPerformed(evt);
            }
        });

        deleteInput.setBackground(new java.awt.Color(255, 51, 51));
        deleteInput.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        deleteInput.setForeground(new java.awt.Color(51, 51, 0));
        deleteInput.setText("suprimer");
        deleteInput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        deleteInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInputActionPerformed(evt);
            }
        });

        addInput.setBackground(new java.awt.Color(51, 255, 51));
        addInput.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        addInput.setForeground(new java.awt.Color(51, 0, 51));
        addInput.setText("Ajouter");
        addInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInputActionPerformed(evt);
            }
        });

        jSeparator10.setForeground(new java.awt.Color(102, 102, 0));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator15.setForeground(new java.awt.Color(102, 102, 0));
        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator16.setForeground(new java.awt.Color(102, 102, 0));
        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(addInput)
                .addGap(32, 32, 32)
                .addComponent(deleteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(prevInput)
                .addGap(31, 31, 31)
                .addComponent(nextInput)
                .addGap(18, 18, 18)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(serchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(serchInput, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(addInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabelInput.setOpaque(true);
        tabelInput.setRowHeight(30);
        tabelInput.getTableHeader().setReorderingAllowed(false);
        jScrollTabelTransaksi11.setViewportView(tabelInput);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi11)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi11, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stock d'entrer", jPanel8);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        serchProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serchProductKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setText("Chercher");

        nextProduct.setBackground(new java.awt.Color(255, 255, 204));
        nextProduct.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        nextProduct.setForeground(new java.awt.Color(51, 51, 0));
        nextProduct.setText("Next");
        nextProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        nextProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextProductActionPerformed(evt);
            }
        });

        prevProduct.setBackground(new java.awt.Color(255, 255, 204));
        prevProduct.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        prevProduct.setForeground(new java.awt.Color(51, 51, 0));
        prevProduct.setText("Prev");
        prevProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        prevProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevProductActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(102, 102, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator11.setForeground(new java.awt.Color(102, 102, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prevProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextProduct)
                .addGap(8, 8, 8)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addComponent(serchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prevProduct)
                        .addComponent(nextProduct)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(serchProduct)
        );

        tabelProduit.setIntercellSpacing(new java.awt.Dimension(10, 5));
        tabelProduit.setOpaque(true);
        tabelProduit.setRowHeight(30);
        tabelProduit.getTableHeader().setReorderingAllowed(false);
        jScrollTabelTransaksi9.setViewportView(tabelProduit);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi9, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollTabelTransaksi9, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Les Produits", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serchSalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serchSalleKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_serchSalleKeyReleased

    private void nextPurchase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPurchase1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPurchase1ActionPerformed

    private void prevSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevSalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevSalleActionPerformed

    private void deleteSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteSalleActionPerformed

    private void addSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalleActionPerformed
        new SalleForm("vente");
        refrech();  
    }//GEN-LAST:event_addSalleActionPerformed

    private void serchInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serchInputKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_serchInputKeyReleased

    private void nextInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextInputActionPerformed

    private void prevInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevInputActionPerformed

    private void deleteInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteInputActionPerformed

    private void addInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInputActionPerformed
        new SalleForm("input");
          refrech();   
        // TODO add your handling code here:
    }//GEN-LAST:event_addInputActionPerformed

    private void serchProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serchProductKeyReleased
        String text = serchProduct.getText();
        loadSearchDataProduct(text);
        // TODO add your handling code here:
    }//GEN-LAST:event_serchProductKeyReleased

    private void nextProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextProductActionPerformed
        ++counterPagination;

        if (counterPagination >= prtbl.countRecords() / limitPagination) {
            nextProduct.setEnabled(false);
            prevProduct.setEnabled(true);
        } else {
            nextProduct.setEnabled(true);
            prevProduct.setEnabled(true);
        }
        tabelProduit.setModel(prtbl.generateTable(limitPagination, counterPagination));

        // TODO add your handling code here:
    }//GEN-LAST:event_nextProductActionPerformed

    private void prevProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevProductActionPerformed
        --counterPagination;
        // Set Tabel Model for Barang
        if (counterPagination * limitPagination <= 0) {
            prevProduct.setEnabled(false);
            nextProduct.setEnabled(true);
        } else {
            prevProduct.setEnabled(true);
            nextProduct.setEnabled(true);
        }
        tabelProduit.setModel(prtbl.generateTable(limitPagination, counterPagination));
        // TODO add your handling code here:
    }//GEN-LAST:event_prevProductActionPerformed

    private void sallePAge2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sallePAge2ActionPerformed
retour();        // TODO add your handling code here:
    }//GEN-LAST:event_sallePAge2ActionPerformed
private String getCureentTime() {

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date dates = new Date();

        return dateFormat.format(dates);

    }
    private void loadData() throws SQLException {
        tabelProduit.setModel(prtbl.generateTable(limitPagination, counterPagination));
 
   
        tabelSalle.setModel(new SalleTable("vente").generateTable(limitPagination, counterPagination));
        tabelInput.setModel(new SalleTable("input").generateTable(limitPagination, counterPagination));
    }

    // public void loadSearchDataProduct(String text) {
    //     try {
    //         tabelProduit.setModel(prtbl.generateTable4Search(text));
    //     } catch (Exception throwables) {
    //         throwables.printStackTrace();
    //     }

    // }

    public void loadSearchDataPurchase(String text) {

        // try {
        //     ProductDAO productDAO = new ProductDAO();
        //     tabelIPurchase.setModel(productDAO.buildTableModel(productDAO.getPurchaseSearch(text)));
        // } catch (SQLException e) {
        //     e.printStackTrace();
        // }
    }
    
    public void loadSearchDataProduct(String text) {
        try {
            tabelProduit.setModel(prtbl.generateTable4Search(text));
        } catch (Exception throwables) {
            throwables.printStackTrace();
        }

    }    
    void refrech() {
        try {
            loadData();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
    private void retour() {
        new FristPage(username).setVisible(true);
            dispose();
         
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInput;
    private javax.swing.JButton addSalle;
    private javax.swing.JButton deleteInput;
    private javax.swing.JButton deleteSalle;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollTabelTransaksi11;
    private javax.swing.JScrollPane jScrollTabelTransaksi8;
    private javax.swing.JScrollPane jScrollTabelTransaksi9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton nextInput;
    private javax.swing.JButton nextProduct;
    private javax.swing.JButton nextPurchase1;
    private javax.swing.JButton prevInput;
    private javax.swing.JButton prevProduct;
    private javax.swing.JButton prevSalle;
    private javax.swing.JButton sallePAge2;
    private javax.swing.JTextField serchInput;
    private javax.swing.JTextField serchProduct;
    private javax.swing.JTextField serchSalle;
    private javax.swing.JTable tabelInput;
    private javax.swing.JTable tabelProduit;
    private javax.swing.JTable tabelSalle;
    // End of variables declaration//GEN-END:variables
}
